settings:
    resource: "@SettingsBundle/Controller/"
    type:     annotation
    prefix:   /

report:
    resource: "@ReportBundle/Controller/"
    type:     annotation
    prefix:   /

ingredient:
    resource: "@IngredientBundle/Controller/"
    type:     annotation
    prefix:   /

cup:
    resource: "@CupBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation